spring.application.name=edusphere
spring.datasource.url=jdbc:mysql://localhost:3306/edusphere
spring.datasource.username=root
spring.datasource.password=Harsh@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ZmY5NjY2YjJlODQ4OWI2MWY2NzYxMzFkYzI5YjVkNWE2YjY4Y2M3ZGM4YjU4ZGM2MjA2MjA3ZjYzMzM0NQ==
jwt.expiration=900000
